{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spring-service.serviceAccountName" . }}
  labels:
{{ include "spring-service.labels" . | nindent 4 }}
{{- end -}}
